

import Header from "@/components/Header";
import "./globals.css";
import { JetBrains_Mono } from 'next/font/google';
import PageTransition from "@/components/PageTransition";
import StairTransition from "@/components/StairTransition";

const jetBrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-jetBrainsMono",
  weight: ["100","200","300","400","500","600","700","800"]
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function
 RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${jetBrainsMono.variable} bg-neutral-900`}
      >
        <Header />
        <StairTransition />
        <PageTransition className="container">
          {children}
        </PageTransition>
      </body>
    </html>
  );
}
